```{r}
library(tidyverse)
library(ggplot2)
library(stringr)
library(ggrastr)
library(dplyr)
library(Seurat)
library(scales)
library(cowplot)
#library(fmsb)
library(fgsea)
library(ZemmourLib)
library(pheatmap)
library(RColorBrewer)
library(viridisLite)
#setwd("/Users/nityamehrotra/Library/CloudStorage/Box-Box/ZemmourLab_Nitya/CD4")
cd4_object <- readRDS("CD4_igt1_96_withtotalvi20260206_clean.Rds")
color_palette <- read.csv("immgent_color_palettes_level2.csv", header = FALSE)
palette_vector <- setNames(
  as.character(color_palette$V2), 
  as.character(color_palette$V1))

organ_palette <- read.csv("immgent_color_palettes_organ_simplified.csv", header = FALSE)
palette_vector_organ <- setNames(organ_palette$V2, organ_palette$V1)


condition_palette <- read.csv("immgent_colors_level1.csv", header = FALSE)
palette_level1 <- setNames(condition_palette$V2, condition_palette$V1)

cd4_object <- NormalizeData(
  cd4_object,
  assay = "RNA",
  normalization.method = "LogNormalize"
)
```

```{r}
#Figure 1b - CD4 MDE w/ immgent color palette
pdf("052726_cd4_mde.pdf", width = 8, height = 8, useDingbats = FALSE)
DimPlot(cd4_object, reduction = "mde_incremental", group.by = "annotation_level2", cols = palette_vector, label = TRUE, raster = TRUE, raster.dpi = c(1024, 1024)) + ggtitle("CD4 T Cells in All Populations") + NoAxes() + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))
dev.off()
```

```{r}
#1c - cd62l x cd44 feature plots for resting/activated
cd4_cite <- subset(cd4_object, subset = cite_seq == "TRUE")
cd4_cite <- NormalizeData(cd4_cite, assay = "ADT", normalization.method = "LogNormalize")

resting_clusters <-c("CD4.A", "CD4.B", "CD4.C", "CD4.D", "CD4.E", "CD4.F")
cd4_resting <- subset(cd4_cite, subset = annotation_level2 %in% resting_clusters)
cd4_resting$not_cl6 <- cd4_resting$annotation_level2 != "CD4_cl6"
p <- MyFeatureScatter(
  so = cd4_resting,
  group.by = "not_cl6",
  feature1 = "CD62L",
  feature2 = "CD44",
  raster = TRUE
)
pdf("052726_featscatter_cd4_resting_cd44xcd62l.pdf", height = 8, width = 8, useDingbats = FALSE)
print(p)
dev.off()

activated_clusters <- c("CD4.G", "CD4.H", "CD4.I", "CD4.Q", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y")
cd4_activated <- subset(cd4_cite, subset = annotation_level2 %in% activated_clusters)
cd4_activated$not_cl6 <- cd4_activated$annotation_level2 != "CD4_cl6"
p <- MyFeatureScatter(
  so = cd4_activated,
  group.by = "not_cl6",
  feature1 = "CD62L",
  feature2 = "CD44",
  raster = TRUE
)
pdf("052726_featscatter_cd4_activated_cd44xcd62l.pdf", height = 8, width = 8, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#1d - condition dotplot
cd4_object@meta.data <- cd4_object@meta.data %>%
  mutate(
    condition_detailed_simplified = trimws(as.character(condition_detailed_simplified)),
    condition_detailed            = trimws(as.character(condition_detailed)),
    condition_broad               = trimws(as.character(condition_broad))
  )

cd4_object@meta.data <- cd4_object@meta.data %>%
  mutate(
    condition_detailed_simplified = ifelse(
      condition_detailed %in% c("12mo", "18mo", "27mo"),
      "aging",
      condition_detailed_simplified
    )
  )

cd4_object@meta.data <- cd4_object@meta.data %>%
  mutate(
    condition_detailed_simplified = case_when(
      condition_detailed_simplified %in% c("SFB", "SFB_pregnancy") ~ "SFB",
      TRUE ~ condition_detailed_simplified
    )
  )


cd4_object@meta.data <- cd4_object@meta.data %>%
  mutate(
    condition_detailed_simplified = case_when(
      condition_detailed_simplified %in% c("PDAC", "PDAC_aPD1aCTLA4", "PDAC_FishHFD", "PDAC_SoyHFD") ~ "PDAC",
      condition_detailed_simplified %in% c("GBMclass", "GBMclass_aPD1aCTLA4",
                                           "GBMmes", "GBMmes_aPD1aCTLA4",
                                           "GBMpron", "GBMpron_aPD1aCTLA4") ~ "GBM",
      condition_detailed_simplified %in% c("B16_ACT", "B16_ACTaPD1a41BB") ~ "B16",
      condition_detailed_simplified %in% c("HeartTransplant_rejection",
                                           "HeartTransplant_tolerance") ~ "HeartTransplant",
      TRUE ~ condition_detailed_simplified
    )
  )

cd4_object <- subset(
  cd4_object,
  subset = !condition_detailed_simplified %in% c(
    "MHCIIhet_Ea16", "MHCIIhet",
    "MHCIIKO_Ea16", "MHCIIKO",
    "KbDbKO", "KbDbKO_MCMV",
    "KbDbQa1KO", "KbDbQa1KO_MCMV", "other"
  )
)


cd4_object <- subset(
  cd4_object,
  subset = !(condition_detailed_simplified == "B16" &
             condition_broad == "healthy")
)

sample_counts <- table(cd4_object$sample_name)
keep_samples  <- names(sample_counts[sample_counts > 10])

cd4_filt <- subset(cd4_object, subset = sample_name %in% keep_samples)

cd4_filt@meta.data <- cd4_filt@meta.data %>%
  mutate(
    condition_detailed_simplified = trimws(as.character(condition_detailed_simplified))
  )

cond_col    <- "condition_detailed_simplified"
cluster_col <- "annotation_level2"
broad_col   <- "condition_broad"

base_size <- 6.5
axis_size <- 6

cd4_metadata <- cd4_filt@meta.data

broad_order <- c(
  "healthy", "bacteria", "fungus", "virus", "parasite",
  "multiinfection", "autoimmune", "allergy", "cancer",
  "immunization", "allotransplant"
)

cd4_metadata <- cd4_metadata %>%
  mutate(
    condition_broad = factor(condition_broad, levels = broad_order)
  )

cond_to_broad <- cd4_metadata %>%
  count(
    condition = .data[[cond_col]],
    broad     = .data[[broad_col]],
    name = "cells"
  ) %>%
  group_by(condition) %>%
  slice_max(cells, n = 1, with_ties = FALSE) %>%
  ungroup()

dotplot <- cd4_metadata %>%
  count(
    condition = .data[[cond_col]],
    cluster   = .data[[cluster_col]],
    name = "n"
  ) %>%
  left_join(cond_to_broad, by = "condition") %>%
  filter(!is.na(condition), !is.na(cluster), !is.na(broad)) %>%
  group_by(condition) %>%
  mutate(total = sum(n), prop = n / total) %>%
  ungroup() %>%
  mutate(
    n_log10 = log10(n + 1),
    broad   = factor(broad, levels = broad_order)
  )

cond_levels <- dotplot %>%
  distinct(condition, broad, total) %>%
  arrange(broad, desc(total), condition) %>%
  pull(condition)

dotplot <- dotplot %>%
  mutate(condition = factor(condition, levels = rev(cond_levels)))
side <- dotplot %>% distinct(condition, broad)
broad_levels <- levels(droplevels(dotplot$broad))

broad_cols <- c(
  "lightblue4", "lightblue1", "purple4", "green4", "yellow3",
  "lightyellow3", "pink3", "orange", "pink4", "orange4", "darkred"
)
broad_cols <- broad_cols[seq_len(length(broad_levels))]
names(broad_cols) <- broad_levels


p_side <- ggplot(side, aes(x = 1, y = condition, fill = broad)) +
  geom_tile() +
  scale_fill_manual(values = broad_cols, drop = FALSE) +
  scale_y_discrete(expand = expansion(mult = c(0.01, 0.01))) +
  theme_void() +
  theme(
    legend.position = "bottom",
    legend.title = element_text(size = base_size - 1),
    legend.text  = element_text(size = base_size - 2),
    legend.key.height = unit(0.18, "cm"),
    legend.key.width  = unit(0.38, "cm"),
    legend.key = element_rect(color = "black", linewidth = 0.3),
    plot.margin = margin(0, 0, 0, 0)
  ) +
  guides(fill = guide_legend(title = "Condition broad", nrow = 2, byrow = TRUE))

legend_broad <- get_legend(p_side)
p_side_noleg <- p_side +
  theme(legend.position = "none") +
  theme(plot.margin = margin(2, 0, 2, 0))

p_main <- ggplot(dotplot, aes(x = cluster, y = condition)) +
  geom_point(aes(size = n_log10, fill = prop),
             shape = 21, color = "black", stroke = 0.1) +
  scale_fill_gradient(low = "white", high = "darkgreen",
                      limits = c(0, 0.25), oob = squish) +
  scale_size_continuous(name = "Cells per dot (log10)", range = c(1.5, 4)) +
  theme_bw(base_size = base_size) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(size = axis_size - 1, angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size = axis_size - 1, lineheight = 0.75),
    panel.grid = element_blank(),
    panel.border = element_rect(linewidth = 0.1),
    plot.margin = margin(2, 2, 2, 0)
  ) +
  guides(
    size = guide_legend(title = "Cells per dot (log10)"),
    fill = guide_colorbar(title = "Mean proportion")
  )

bottom_row <- plot_grid(
  p_side_noleg, p_main,
  ncol = 2, rel_widths = c(0.02, 0.98),
  align = "h", axis = "tb"
)

pdf("052726_1c_condition_dotplot.pdf",
    width = 5.0, height = 4.5, useDingbats = FALSE)
plot_grid(legend_broad, bottom_row, ncol = 1, rel_heights = c(0.05, 0.95))
dev.off()
```

```{r}
#1c - organ dotplot for each condition
cond_order <- rev(levels(dotplot$condition))
organ_order <- c("spleen", "LN", "blood", "bone marrow","lung", "colon","small intestine", "skin", "kidney", "liver", "pancreas", "submandibular gland", "synovial fluid", "placenta", "uterus", "prostate", "mammary gland", "peritoneal cavity","CNS")

org_df <- cd4_filt@meta.data %>%
  mutate(
    condition = trimws(as.character(condition_detailed_simplified)),
    organ     = trimws(as.character(organ_simplified))
  ) %>%
  filter(!is.na(condition), condition != "",
         !is.na(organ), organ != "") %>%
  distinct(condition, organ) %>%
  mutate(
    condition = factor(condition, levels = rev(cond_order)),
    organ     = factor(organ, levels = organ_order)
  ) %>%
  filter(!is.na(condition), !is.na(organ))

p_org_presence <- ggplot(org_df, aes(x = organ, y = condition)) +
  geom_point(
    aes(fill = organ),
    shape = 21,
    size = 2.0,
    color = "black",
    stroke = 0.1
  ) +
  scale_x_discrete(drop = FALSE) + 
  scale_fill_manual(values = palette_vector_organ, drop = FALSE) +
  scale_y_discrete(na.translate = FALSE) +
  theme_bw(base_size = base_size) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(size = axis_size - 1, angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y = element_text(size = axis_size - 1, lineheight = 0.75),
    panel.grid = element_blank(),
    panel.border = element_rect(linewidth = 0.1),
    plot.margin = margin(2, 2, 2, 2)
  )

pdf("052726_1c_organ_dotplot.pdf", width = 3.0, height = 4.5, useDingbats = FALSE)
print(p_org_presence)
dev.off()
```

```{r}
#1e - dotplot of selected markers
gene_markers <- c("Sell", "Cd44", "Bcl6", "Cxcr5", "Tox", "Tox2", "Tigit", "Lag3", "Ctla4", "Havcr2", "Il21", "Pdcd1", "Izumo1r", "Tnfrs4", "Tbx21", "Ifng", "Gzma", "Gzmb", "Gata3", "Il4", "Il5", "Il13", "Rorc", "Il17a", "Il22", "Il10")

DefaultAssay(cd4_object) <- "RNA"

genes_use <- intersect(gene_markers, rownames(cd4_object[["RNA"]]))
cd4_object <- NormalizeData(cd4_object, assay = "RNA", normalization.method = "LogNormalize", layer = "data")

dp <- DotPlot(
  cd4_object,
  features = genes_use,
  group.by = "annotation_level2",
  assay = "RNA"
)

dp_df <- dp$data

remove_ids <- c("CD4.P", "CD4.wM", "CD4.wN", "CD4.wZ")
dp_df <- dp_df %>%
  filter(!id %in% remove_ids)

dp_df$id <- droplevels(dp_df$id)

dp_df$features.plot <- factor(dp_df$features.plot, levels = rev(genes_use))


base_size <- 10
axis_size <- 9

p_rna <- ggplot(dp_df, aes(x = id, y = features.plot)) +
  geom_point(
    aes(size = pct.exp, fill = avg.exp.scaled),
    shape = 21,
    color = "black",
    stroke = 0.12
  ) +
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "red",
    midpoint = 0,
    oob = squish,
    name = "Avg expr (scaled)"
  ) +
  scale_size_continuous(
    name = "% expressing",
    range = c(0.5, 4),
    breaks = c(0, 25, 50, 75, 100),
    limits = c(0, 100)
  ) +
  scale_y_discrete(expand = expansion(mult = c(0.03, 0.03))) +
  scale_x_discrete(expand = expansion(mult = c(0.04, 0.04))) +
  theme_bw(base_size = base_size) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(
      size = axis_size,
      angle = 90,
      vjust = 0.5,
      hjust = 1,
      margin = margin(t = 1)
    ),
    axis.text.y = element_text(
      size = axis_size,
      lineheight = 0.85,
      margin = margin(r = 1)
    ),
    panel.grid = element_blank(),
    panel.border = element_rect(linewidth = 0.12),
    plot.margin = margin(2, 2, 2, 2),
    legend.title = element_text(size = base_size),
    legend.text  = element_text(size = base_size - 1)
  ) +
  guides(
    size = guide_legend(title = "% expressing"),
    fill = guide_colorbar(title = "Avg expr (scaled)")
  )

pdf("052726_1e_RNA_dotplot.pdf", width = 4.5, height = 2.5, useDingbats = FALSE)
print(p_rna)
dev.off()
```

```{r}
#Figure s1 - chemokine receptor feature plots
cd4_object_sub <- subset(cd4_object, subset = !(annotation_level2 %in% c("CD4.wM", "CD4.P")))
cd4_object_sub <-  NormalizeData(cd4_object_sub, assay = "RNA", normalization.method = "LogNormalize")
diet = DietSeurat(object = cd4_object_sub, layers = c("counts", "data"), assays = c("RNA"), features = c("Cxcr4", "Ccr7", "Cxcr3", "Ccr5", "Ccr4", "Ccr6", "Cxcr5", "Ccr2", "Ccr9", "Ccr10", "Cxcr6", "Cx3cr1"), dimreducs = c("mde_incremental"))


FeaturePlot(diet, reduction = "mde_incremental", features = c("Cx3cr1"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

dev.off()
FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr7"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Cxcr3"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr5"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr4"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr6"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Cxcr5"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr2"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr9"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Ccr10"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Cxcr6"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

```


```{r}
#2a - highlighting midlands and tips
cd4_object$is_gq <- cd4_object$annotation_level2 %in% c("CD4.G", "CD4.Q")
cells_gq <- colnames(cd4_object)[cd4_object$is_gq]
plots_gq <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_gq,
  highlight_column_name = "annotation_level2",
  title                 = "CD4.Q and CD4.G cells highlighted",
  labelclusters = FALSE,
  highlight_raster = T,
  highlight_pixels =  c(1024, 1024),
  mycols = palette_vector,
  highlight_size = 1,
  highlight_alpha = 1,
  background_alpha = 1.0,
  pixels = c(512,512)
)

p <- print(plots_gq$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))

pdf("052726_midlands_highlighted.pdf", width = 8, height =8, useDingbats = FALSE)
print(p)
dev.off()

#tips
cd4_object$is_tips <- cd4_object$annotation_level2 %in% c("CD4.H", "CD4.I", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y")
cells_tips <- colnames(cd4_object)[cd4_object$is_tips]
plots_tips <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_tips,
  highlight_column_name = "annotation_level2",
  title                 = "CD4 Tip cells highlighted",
  labelclusters = FALSE,
  highlight_raster = T,
  highlight_pixels = c(1024, 1024),
  mycols = palette_vector,
  highlight_size = 1,
  highlight_alpha = 1,
  background_alpha = 1.0,
  pixels = c(512,512)
)


p <- print(plots_tips$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))

p
pdf("052726_tips_highlighted.pdf", width = 8, height = 8, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#2b/c - feature plots of cytokine genes/TFs
cd4_object <- NormalizeData(cd4_object, assay = "ADT", normalization.method = "LogNormalize")
cd4_object <-  NormalizeData(cd4_object, assay = "RNA", normalization.method = "LogNormalize")
diet = DietSeurat(object = cd4_object, layers = c("counts", "data"), assays = c("RNA", "ADT"), features = c("Tbx21", "Ifng", "Rorc", "Il17a", "Gata3", "Il5", "Bcl6", "Il21"), dimreducs = c("mde_incremental"))

pdf("052726_2cd_featureplots_genes.pdf", h = 8, w = 8, useDingbats = F)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Tbx21"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Gata3"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Rorc"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Bcl6"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)


FeaturePlot(diet, reduction = "mde_incremental", features = c("Ifng"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Il5"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)
dev.off()

FeaturePlot(diet, reduction = "mde_incremental", features = c("Il17a"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)

FeaturePlot(diet, reduction = "mde_incremental", features = c("Il21"), order = T,  min.cutoff = "q20", max.cutoff = "q99",  cols = c("lightgrey", "blue") , raster = F, raster.dpi = c(512,512)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + NoAxes() + NoLegend() + theme_void() + theme(legend.position = "none") #cols = c("lightgrey", "blue") rocket(10, direction = -1)
dev.off()
```

```{r}
#2d - condition mdes
#tgondii
cd4_object$is_toxod9 <- cd4_object$condition_detailed %in% c("Toxo_D9")
cells_toxo <- colnames(cd4_object)[cd4_object$is_toxod9]
plots_toxo <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_toxo,
  highlight_column_name = "annotation_level2",
  title                 = "CD4 Tip cells highlighted",
  labelclusters = FALSE,
  mycols = palette_vector,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  background_alpha = 1.0,
  pixels = c(512,512)
)
p <- print(plots_toxo$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))

pdf("052726_toxo_highlighted.pdf", width = 8, height = 8, useDingbats = FALSE)
print(p)
dev.off()

#tmuris
cd4_object$is_tmuris <- cd4_object$condition_detailed_simplified %in% c("Tmuris")
cells_tmuris <- colnames(cd4_object)[cd4_object$is_tmuris]
plots_tmuris <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_tmuris,
  highlight_column_name = "annotation_level2",
  title                 = "CD4 Tip cells highlighted",
  labelclusters = FALSE,
  mycols = palette_vector,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  background_alpha = 1.0,
  pixels = c(512,512)
)
p <- print(plots_tmuris$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))
p
pdf("052726_2d_tmuris_highlighted.pdf", width = 8, height = 8, useDingbats = FALSE)
print(p)
dev.off()
#sfb ileum
cd4_object$is_sfb <- cd4_object$condition_detailed_simplified %in% "SFB" & cd4_object$organ == "ileum lamina propria"

cells_is_sfb <- colnames(cd4_object)[cd4_object$is_sfb]
plots_is_sfb <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_is_sfb,
  highlight_column_name = "annotation_level2",
  labelclusters = FALSE,
  mycols = palette_vector,
  highlight_size = 1.0,
  highlight_alpha = 1.0,
  background_alpha = 1.0,
  pixels = c(512,512)
)
p <- print(plots_is_sfb$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))
p
pdf("052726_2d_sfb_highlighted.pdf", width = 8, height = 8, useDingbats = FALSE)
print(p)
dev.off()

#np ova 7dpi
cd4_object$is_npova <- cd4_object$condition_detailed %in% c("NP_OVA_D7")

cells_npova <- colnames(cd4_object)[cd4_object$is_npova]
plots_npova <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_npova,
  highlight_column_name = "annotation_level2",
  labelclusters = FALSE,
  mycols = palette_vector,
  highlight_size = 0.5,
  highlight_alpha = 0.8,
  background_alpha = 1.0,
  pixels = c(512,512)
)
p <- print(plots_npova$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))
p
pdf("052726_2d_npova_highlighted.pdf", width = 8, height = 8, useDingbats = FALSE)
print(p)
dev.off()

```

```{r}
#2e - effector genes/cytokine heatmap
sub <- subset(cd4_object, subset = annotation_level2 %in% c("CD4.G", "CD4.H", "CD4.I", "CD4.Q", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y"))

genes <- c("Ifng","Il4","Il5","Il17a","Il17f","Gzma","Gzmb","Il4", "Il5","Il10","Il21","Il22", "Il13")

gene_order <- c("Il21", "Ifng", "Gzma", "Gzmb","Il10" ,"Il4", "Il5", "Il13", "Il17a", "Il17f", "Il22")

cluster_order <- c("CD4.G","CD4.H","CD4.I","CD4.Q","CD4.R", "CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y")

effector <- FetchData(sub, vars = c(genes, "annotation_level2"))

effector <- effector %>%
  filter(annotation_level2 %in% cluster_order)

eff_long <- effector %>%
  pivot_longer(
    cols = all_of(genes),
    names_to = "gene",
    values_to = "expr"
  )

eff_long <- eff_long %>%
  mutate(expr_bin = expr > 0)

counts <- eff_long %>%
  filter(expr_bin) %>%
  group_by(gene, annotation_level2) %>%
  summarise(n = n(), .groups = "drop")

props <- counts %>%
  group_by(gene) %>%
  mutate(prop = n / sum(n)) %>%
  ungroup()

props$annotation_level2 <- factor(props$annotation_level2,
                                  levels = cluster_order)

props <- props %>%
  mutate(
    annotation_level2 = factor(annotation_level2, levels = cluster_order),
    gene = factor(gene, levels = gene_order)
  ) %>%
  droplevels()


props_full <- props %>%
  mutate(
    annotation_level2 = factor(annotation_level2, levels = cluster_order),
    gene = factor(gene, levels = gene_order)
  ) %>%
  complete(gene, annotation_level2, fill = list(prop = 0))

mat_pct <- props_full %>%
  mutate(pct = prop * 100) %>%
  select(gene, annotation_level2, pct) %>%
  pivot_wider(names_from = annotation_level2, values_from = pct) %>%
  arrange(gene)

mat <- as.matrix(mat_pct[,-1])
rownames(mat) <- as.character(mat_pct$gene)

white_red <- colorRampPalette(c("white", "red"))(101)

display_numbers <- matrix("", nrow = nrow(mat), ncol = ncol(mat))

display_numbers[mat > 0 & mat < 1]  <- sprintf("%.2f", mat[mat > 0 & mat < 1])
display_numbers[mat > 1 & mat < 10]  <- sprintf("%.1f", mat[mat > 1 & mat < 10])
display_numbers[mat >= 10]           <- sprintf("%.0f", mat[mat >= 10])

display_numbers <- matrix(display_numbers, nrow = nrow(mat)) 

pdf("052726_effector_counts_heatmap.pdf", width = 8, height = 4.5, useDingbats = FALSE)
pheatmap(
  mat,
  color = white_red,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  border_color = "darkgray",
  display_numbers = display_numbers,
  number_color = "black",
  fontsize_number = 7,
  angle_col = 45,
  cellwidth = 20,
  cellheight = 20
)
dev.off()
```

```{r}
#2f - boxplots of % tips in organs
ann_col   <- "annotation_level2"
sample_col <- "sample_code"
organ_col  <- "organ_simplified"
cond_col   <- "condition_broad"
activated     <- c("CD4.G","CD4.H","CD4.I","CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y")
tips <- c("CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y", "CD4.H", "CD4.I")

organ_order <- c(
  "spleen","LN","blood","bone marrow","thymus","lung",
  "colon LP","small intestine LP","skin","kidney","liver",
  "pancreas","submandibular gland","synovial fluid","placenta",
  "uterus","prostate","mammary gland","peritoneal cavity","CNS"
)

props2 <- FetchData(cd4_object, vars = c(ann_col, sample_col, organ_col, cond_col)) %>%
  rownames_to_column("cell") %>%
  transmute(
    cell,
    annotation  = .data[[ann_col]],
    sample_code = .data[[sample_col]],
    organ       = .data[[organ_col]],
    condition   = .data[[cond_col]]
  ) %>%
  filter(
    !is.na(sample_code), !is.na(organ), !is.na(condition),
    condition == "healthy",
    annotation %in% activated
  ) %>%
  group_by(organ, sample_code) %>%
  summarise(
    prop = sum(annotation %in% tips) / n(),
    .groups = "drop"
  ) %>%
  mutate(organ = factor(organ, levels = organ_order)) %>%
  filter(organ %in% organ_order)

p <- ggplot(props2, aes(x = organ, y = prop, fill = organ)) +
  geom_boxplot(width = 0.6, outlier.shape = NA, alpha = 0.8) +
  geom_point(position = position_jitter(width = 0.15), size = 0.6) +
  scale_fill_manual(values = palette_vector_organ) +
  scale_y_continuous(limits = c(0, 1), labels = percent_format(accuracy = 1)) +
  theme_classic() +
  theme(legend.position = "none", axis.text.x = element_text(angle = 60, hjust = 1)) +
  labs(x = NULL, y = "% tips within activated CD4 T Cells (healthy)")

pdf("052726_organ_tips_within_activated.pdf", width = 8, height = 5, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#2g - prop of tips across activated cells in healthy vs nonhealthy colon, lung, spleen
ann_col    <- "annotation_level2"
sample_col <- "sample_code"
organ_col  <- "organ_simplified"
cond_col   <- "condition_broad"

activated     <- c("CD4.G","CD4.H","CD4.I","CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y")
tips <- c("CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y")

organs_keep  <- c("spleen", "colon LP", "lung")
cond_levels  <- c("healthy", "nonhealthy")

df_all <- FetchData(
  cd4_object,
  vars = c(ann_col, sample_col, organ_col, cond_col),
  layer = "data"
) %>%
  rownames_to_column("cell") %>%
  transmute(
    cell,
    annotation  = .data[[ann_col]],
    sample_code = .data[[sample_col]],
    organ       = .data[[organ_col]],
    condition   = .data[[cond_col]]
  ) %>%
  filter(
    !is.na(sample_code),
    !is.na(organ),
    !is.na(condition),
    organ %in% organs_keep,
    annotation %in% activated
  ) %>%
  mutate(
    cond2 = if_else(condition == "healthy", "healthy", "nonhealthy")
  )

props2 <- df_all %>%
  group_by(organ, sample_code, cond2) %>%
  summarise(
    n_activated = n(),
    n_tips  = sum(annotation %in% tips),
    prop         = n_tips / n_activated,
    .groups = "drop"
  ) %>%
  mutate(
    organ = factor(organ, levels = organs_keep),
    cond2 = factor(cond2, levels = cond_levels),
    organ_cond = factor(
      paste(organ, cond2),
      levels = as.vector(t(outer(organs_keep, cond_levels, paste)))
    )
  )

p <- ggplot(props2, aes(x = organ_cond, y = prop, fill = organ)) +
  geom_boxplot(width = 0.6, outlier.shape = NA, alpha = 0.8) +
  geom_point(
    position = position_jitter(width = 0.15),
    size  = 0.6,
    alpha = 1.0
  ) +
  scale_fill_manual(values = palette_vector_organ) +
  scale_y_continuous(
    limits = c(0, 1),
    labels = scales::percent_format(accuracy = 1)
  ) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.text.x = element_text(angle = 60, hjust = 1)
  ) +
  labs(
    x = NULL,
    y = "% tips within activated CD4 T Cells (healthy vs nonhealthy)"
  )

pdf("052726_boxplot_healthyvsnonhealthy_tips_within_activated.pdf",
    width = 5, height = 4, useDingbats = FALSE)
print(p)
dev.off()

```

```{r}
#3e - single cell heatmap, downsampled, g/q ordered by program
xy_genes <- readLines("XY_vs_RSTUHI_up.txt")
rs_genes <- readLines("RS_vs_TUXYHI_up.txt")
tu_genes <- readLines("TU_vs_RSXYHI_up.txt")
hi_genes <- readLines("HI_vs_RSTUXY_up.txt")

cd4_object <- AddModuleScore(
  object = cd4_object,
  features = list(rs_genes),
  name = "TH1_Score"
)

cd4_object <- AddModuleScore(
  object = cd4_object,
  features = list(tu_genes),
  name = "TH2_Score"
)

cd4_object <- AddModuleScore(
  object = cd4_object,
  features = list(xy_genes),
  name = "TH17_Score"
)

cd4_object <- AddModuleScore(
  object = cd4_object,
  features = list(hi_genes),
  name = "TFH_TCHRON_Score"
)


cluster_order <- c("CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y","CD4.H","CD4.I","CD4.Q","CD4.G")
polyfunctional <- readRDS("CD4_GHIQRSTUXY_igt1_96_withtotalvi20260206_clean_withThPrograms.Rds")
score_cols <- c("TH1_Score1", "TH2_Score1", "TH17_Score1", "TFH_TCHRON_Score1")
q_no_module_thresh <- 0
g_no_module_thresh <- 0

activated <- subset(cd4_object, subset = annotation_level2 %in% cluster_order)

activated$annotation_level2 <- factor(activated$annotation_level2, levels = cluster_order)
Idents(activated) <- activated$annotation_level2

#downsample to 10k cells per cluster
set.seed(123)
cells_keep <- unlist(lapply(cluster_order, function(cl) {
  cl_cells <- WhichCells(sub, idents = cl)
  if (length(cl_cells) > 10000) {
    sample(cl_cells, 10000)
  } else {
    cl_cells
  }
}))

sub <- subset(activated, cells = cells_keep)

sub$annotation_level2 <- factor(sub$annotation_level2, levels = cluster_order)
Idents(sub) <- sub$annotation_level2

score_mat <- t(as.matrix(sub@meta.data[, score_cols]))
colnames(score_mat) <- colnames(sub)
rownames(score_mat) <- c("Th1 program", "Th2 program", "Th17 program", "Tfh/Tchron program")

sub[["ModuleScore"]] <- CreateAssayObject(data = score_mat)

DefaultAssay(sub) <- "ModuleScore"
sub <- ScaleData(
  sub,
  features = rownames(sub[["ModuleScore"]]),
  do.center = TRUE,
  do.scale = TRUE
)

# pull program labels from polyfunctional object
prog_df <- polyfunctional@meta.data %>%
  select(annotation_level2_program) %>%
  rownames_to_column("cell") %>%
  distinct(cell, .keep_all = TRUE) %>%
  mutate(
    annotation_level2_program_clean = tolower(annotation_level2_program)
  )

meta <- sub@meta.data %>%
  rownames_to_column("cell") %>%
  left_join(prog_df, by = "cell") %>%
  mutate(
    q_max_program = pmax(TH1_Score1, TH2_Score1, TH17_Score1, TFH_TCHRON_Score1, na.rm = TRUE),
    g_max_program = pmax(TH1_Score1, TH2_Score1, TH17_Score1, TFH_TCHRON_Score1, na.rm = TRUE),
    is_q_single_or_none = annotation_level2_program_clean %in% c(
      "cd4.q.none", "cd4.q.th1", "cd4.q.th2", "cd4.q.th17", "cd4.q.tfhchron", "cd4.q.tfh_tchron"
    ),
    is_g_single_or_none = annotation_level2_program_clean %in% c(
      "cd4.g.none", "cd4.g.th1", "cd4.g.th2", "cd4.g.th17", "cd4.g.tfhchron", "cd4.g.tfh_tchron"
    ),
    is_q_polyfunctional = annotation_level2 == "CD4.Q" &
      !is.na(annotation_level2_program_clean) &
      grepl("^cd4\\.q\\.", annotation_level2_program_clean) &
      !is_q_single_or_none,
    is_g_polyfunctional = annotation_level2 == "CD4.G" &
      !is.na(annotation_level2_program_clean) &
      grepl("^cd4\\.g\\.", annotation_level2_program_clean) &
      !is_g_single_or_none,
    q_program = case_when(
      annotation_level2 != "CD4.Q" ~ NA_character_,
      is_q_polyfunctional ~ "CD4.Q_polyfunctional",
      q_max_program < q_no_module_thresh ~ "CD4.Q_none",
      TH1_Score1 >= TH2_Score1 & TH1_Score1 >= TH17_Score1 & TH1_Score1 >= TFH_TCHRON_Score1 ~ "CD4.Q_th1",
      TH2_Score1 >= TH1_Score1 & TH2_Score1 >= TH17_Score1 & TH2_Score1 >= TFH_TCHRON_Score1 ~ "CD4.Q_th2",
      TH17_Score1 >= TH1_Score1 & TH17_Score1 >= TH2_Score1 & TH17_Score1 >= TFH_TCHRON_Score1 ~ "CD4.Q_th17",
      TFH_TCHRON_Score1 >= TH1_Score1 & TFH_TCHRON_Score1 >= TH2_Score1 & TFH_TCHRON_Score1 >= TH17_Score1 ~ "CD4.Q_tfh_tchron",
      TRUE ~ "CD4.Q_none"
    ),
    g_program = dplyr::case_when(
      annotation_level2 != "CD4.G" ~ NA_character_,
      is_g_polyfunctional ~ "CD4.G_polyfunctional",
      g_max_program < g_no_module_thresh ~ "CD4.G_none",
      TH1_Score1 >= TH2_Score1 & TH1_Score1 >= TH17_Score1 & TH1_Score1 >= TFH_TCHRON_Score1 ~ "CD4.G_th1",
      TH2_Score1 >= TH1_Score1 & TH2_Score1 >= TH17_Score1 & TH2_Score1 >= TFH_TCHRON_Score1 ~ "CD4.G_th2",
      TH17_Score1 >= TH1_Score1 & TH17_Score1 >= TH2_Score1 & TH17_Score1 >= TFH_TCHRON_Score1 ~ "CD4.G_th17",
      TFH_TCHRON_Score1 >= TH1_Score1 & TFH_TCHRON_Score1 >= TH2_Score1 & TFH_TCHRON_Score1 >= TH17_Score1 ~ "CD4.G_tfh_tchron",
      TRUE ~ "CD4.G_none"
    ),
    annotation_heatmap = case_when(
      annotation_level2 %in% c("CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y","CD4.H","CD4.I") ~ as.character(annotation_level2),
      annotation_level2 == "CD4.Q" ~ q_program,
      annotation_level2 == "CD4.G" ~ g_program,
      TRUE ~ as.character(annotation_level2)
    )
  )

rownames(meta) <- meta$cell
meta$cell <- NULL
sub@meta.data <- meta

heatmap_order <- c(
  "CD4.R","CD4.S","CD4.T","CD4.U","CD4.X","CD4.Y","CD4.H","CD4.I",
  "CD4.Q_none","CD4.Q_th1","CD4.Q_th2","CD4.Q_th17","CD4.Q_tfh_tchron","CD4.Q_polyfunctional",
  "CD4.G_none","CD4.G_th1","CD4.G_th2","CD4.G_th17","CD4.G_tfh_tchron","CD4.G_polyfunctional"
)

sub$annotation_heatmap <- factor(sub$annotation_heatmap, levels = heatmap_order)

meta <- sub@meta.data %>%
  mutate(cell = rownames(.))

set.seed(123)

randomize_per_group <- function(df, group_name) {
  cells_gr <- df %>%
    filter(annotation_heatmap == group_name) %>%
    pull(cell)

  if (length(cells_gr) == 0) return(NULL)
  sample(cells_gr)
}

cell_order <- c(
  randomize_per_group(meta, "CD4.R"),
  randomize_per_group(meta, "CD4.S"),
  randomize_per_group(meta, "CD4.T"),
  randomize_per_group(meta, "CD4.U"),
  randomize_per_group(meta, "CD4.X"),
  randomize_per_group(meta, "CD4.Y"),
  randomize_per_group(meta, "CD4.H"),
  randomize_per_group(meta, "CD4.I"),
  randomize_per_group(meta, "CD4.Q_none"),
  randomize_per_group(meta, "CD4.Q_th1"),
  randomize_per_group(meta, "CD4.Q_th2"),
  randomize_per_group(meta, "CD4.Q_th17"),
  randomize_per_group(meta, "CD4.Q_tfh_tchron"),
  randomize_per_group(meta, "CD4.Q_polyfunctional"),
  randomize_per_group(meta, "CD4.G_none"),
  randomize_per_group(meta, "CD4.G_th1"),
  randomize_per_group(meta, "CD4.G_th2"),
  randomize_per_group(meta, "CD4.G_th17"),
  randomize_per_group(meta, "CD4.G_tfh_tchron"),
  randomize_per_group(meta, "CD4.G_polyfunctional")
)

cell_order <- unique(cell_order)
cell_order <- cell_order[cell_order %in% colnames(sub)]

module_features <- rownames(sub[["ModuleScore"]])

pdf("052726_scheatmap_polyfunctional_splitprograms.pdf", width = 50, height = 22, useDingbats = FALSE)
DoHeatmap(
  sub,
  features = module_features,
  group.by = "annotation_heatmap",
  assay = "ModuleScore",
  cells = cell_order,
  disp.min = -2,
  disp.max = 2,
  raster = FALSE,
  angle = 90
) +
  theme(
    axis.title = element_blank(),
    axis.text.y = element_text(size = 8),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank()
  ) +
  NoLegend()
dev.off()
```

```{r}
#3f-i scatter plots of module scores - all cluster means, only plot g/q cells
#th1 vs th2
clusters_keep <- c("CD4.Q","CD4.G")

modulescores <- FetchData(
  cd4_object,
  vars = c("TH1_Score1", "TH2_Score1", "TH17_Score1", "TFH_TCHRON_Score1", "annotation_level2")
) %>%
  filter(annotation_level2 %in% clusters_keep)

modulescores <- modulescores %>%
  mutate(
    TH1_Score1 = pmin(TH1_Score1, 2.0),
    TH2_Score1 = pmin(TH2_Score1, 2.0),
    TH17_Score1 = pmin(TH17_Score1, 2.0),
    TFH_TCHRON_Score1 = pmin(TFH_TCHRON_Score1, 2.0)
  )

mean <- modulescores %>%
  group_by(annotation_level2) %>%
  summarise(
    TH1 = mean(TH1_Score1, na.rm = TRUE),
    TH2 = mean(TH2_Score1, na.rm = TRUE),
    TH17 = mean(TH17_Score1, na.rm = TRUE),
    TFH_TCHRON = mean(TFH_TCHRON_Score1, na.rm = TRUE)
  )

clusters_keep_2 <- c("CD4.H","CD4.I", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y")

modulescores2 <- FetchData(
  cd4_object,
  vars = c("TH1_Score1", "TH2_Score1", "TH17_Score1", "TFH_TCHRON_Score1", "annotation_level2")
) %>%
  filter(annotation_level2 %in% clusters_keep_2)


mean2 <- modulescores2 %>%
  group_by(annotation_level2) %>%
  summarise(
    TH1 = mean(TH1_Score1, na.rm = TRUE),
    TH2 = mean(TH2_Score1, na.rm = TRUE),
    TH17 = mean(TH17_Score1, na.rm = TRUE),
    TFH_TCHRON = mean(TFH_TCHRON_Score1, na.rm = TRUE)
  )


quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TH2_Score1 >= 0.25 & TH1_Score1 >= 0 ~ "Q1 (TH2+TH1+)",
    TH2_Score1 <  0.25 & TH1_Score1 >= 0 ~ "Q2 (TH2-TH1+)",
    TH2_Score1 <  0.25 & TH1_Score1 <  0 ~ "Q3 (TH2-TH1-)",
    TH2_Score1 >= 0.25 & TH1_Score1 <  0 ~ "Q4 (TH2+TH1-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH2+TH1+)", "Q2 (TH2-TH1+)", "Q3 (TH2-TH1-)", "Q4 (TH2+TH1-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4gq_modulescore_th1vsth2_withmeans_rasterized.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TH2_Score1, y = TH1_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TH2, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) + 
  geom_point(
    data = mean2,
    aes(x = TH2, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) +
  geom_text(
    data = mean,
    aes(x = TH2, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_text(
    data = mean2,
    aes(x = TH2, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Th2-like module score", y = "Th1-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.2, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()

#th1 vs th17
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TH17_Score1 >= 0.25 & TH1_Score1 >= 0 ~ "Q1 (TH17+TH1+)",
    TH17_Score1 <  0.25 & TH1_Score1 >= 0 ~ "Q2 (TH17-TH1+)",
    TH17_Score1 <  0.25 & TH1_Score1 <  0 ~ "Q3 (TH17-TH1-)",
    TH17_Score1 >= 0.25 & TH1_Score1 <  0 ~ "Q4 (TH17+TH1-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH1+)", "Q2 (TH17-TH1+)", "Q3 (TH17-TH1-)", "Q4 (TH17+TH1-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)


quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4gq_modulescore_th1vsth17_withmeans.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TH17_Score1, y = TH1_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TH17, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  )  + 
  geom_point(
    data = mean2,
    aes(x = TH17, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) +
  geom_text(
    data = mean,
    aes(x = TH17, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_text(
    data = mean2,
    aes(x = TH17, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Th17-like module score", y = "Th1-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.3, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()

#th2 vs th17
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TH17_Score1 >= 0.25 & TH2_Score1 >= 0.25 ~ "Q1 (TH17+TH2+)",
    TH17_Score1 <  0.25 & TH2_Score1 >= 0.25 ~ "Q2 (TH17-TH2+)",
    TH17_Score1 <  0.25 & TH2_Score1 <  0.25 ~ "Q3 (TH17-TH2-)",
    TH17_Score1 >= 0.25 & TH2_Score1 <  0.25 ~ "Q4 (TH17+TH2-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH2+)", "Q2 (TH17-TH2+)", "Q3 (TH17-TH2-)", "Q4 (TH17+TH2-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)


quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4gq_modulescore_th2vsth17_withmeans_rasterized.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TH17_Score1, y = TH2_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TH17, y = TH2, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  )  + 
  geom_point(
    data = mean2,
    aes(x = TH17, y = TH2, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) +
  geom_text(
    data = mean,
    aes(x = TH17, y = TH2, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_text(
    data = mean2,
    aes(x = TH17, y = TH2, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Th17-like module score", y = "Th2-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.3, 1.5), ylim = c(-0.2, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()

#th1 vs tfhchron
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TFH_TCHRON_Score1 >= 0.25 & TH1_Score1 >= 0 ~ "Q1 (TFH_TCHRON+TH1+)",
    TFH_TCHRON_Score1 <  0.25 & TH1_Score1 >= 0 ~ "Q2 (TFH_TCHRON-TH1+)",
    TFH_TCHRON_Score1 <  0.25 & TH1_Score1 <  0 ~ "Q3 (TFH_TCHRON-TH1-)",
    TFH_TCHRON_Score1 >= 0.25 & TH1_Score1 <  0 ~ "Q4 (TFH_TCHRON+TH1-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TFH_TCHRON+TH1+)", "Q2 (TFH_TCHRON-TH1+)", "Q3 (TFH_TCHRON-TH1-)", "Q4 (TFH_TCHRON+TH1-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4act_modulescore_tfhtchronvsth2_withmeans.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TFH_TCHRON_Score1, y = TH1_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TFH_TCHRON, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  )  + 
  geom_point(
    data = mean2,
    aes(x = TFH_TCHRON, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) +
  geom_text(
    data = mean,
    aes(x = TFH_TCHRON, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_text(
    data = mean2,
    aes(x = TFH_TCHRON, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Tfh/Tchron-like module score", y = "Th1-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.50, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()
```

```{r}
#s3 - scatter plots with means - all clusters plotted
clusters_keep <- c("CD4.Q","CD4.G","CD4.H", "CD4.I", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y")

modulescores <- FetchData(
  cd4_object,
  vars = c("TH1_Score1", "TH2_Score1", "TH17_Score1", "TFH_TCHRON_Score1", "annotation_level2")
) %>%
  filter(annotation_level2 %in% clusters_keep)

modulescores <- modulescores %>%
  mutate(
    TH1_Score1 = pmin(TH1_Score1, 2.0),
    TH2_Score1 = pmin(TH2_Score1, 2.0),
    TH17_Score1 = pmin(TH17_Score1, 2.0),
    TFH_TCHRON_Score1 = pmin(TFH_TCHRON_Score1, 2.0)
  )

mean <- modulescores %>%
  group_by(annotation_level2) %>%
  summarise(
    TH1 = mean(TH1_Score1, na.rm = TRUE),
    TH2 = mean(TH2_Score1, na.rm = TRUE),
    TH17 = mean(TH17_Score1, na.rm = TRUE),
    TFH_TCHRON = mean(TFH_TCHRON_Score1, na.rm = TRUE)
  )
#th1 vs th2
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TH2_Score1 >= 0.25 & TH1_Score1 >= 0 ~ "Q1 (TH2+TH1+)",
    TH2_Score1 <  0.25 & TH1_Score1 >= 0 ~ "Q2 (TH2-TH1+)",
    TH2_Score1 <  0.25 & TH1_Score1 <  0 ~ "Q3 (TH2-TH1-)",
    TH2_Score1 >= 0.25 & TH1_Score1 <  0 ~ "Q4 (TH2+TH1-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH2+TH1+)", "Q2 (TH2-TH1+)", "Q3 (TH2-TH1-)", "Q4 (TH2+TH1-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4act_modulescore_th1vsth2_withmeans_rasterized.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TH2_Score1, y = TH1_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TH2, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) + 
  geom_text(
    data = mean,
    aes(x = TH2, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Th2-like module score", y = "Th1-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.2, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()



#th1 vs th17
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TH17_Score1 >= 0.25 & TH1_Score1 >= 0 ~ "Q1 (TH17+TH1+)",
    TH17_Score1 <  0.25 & TH1_Score1 >= 0 ~ "Q2 (TH17-TH1+)",
    TH17_Score1 <  0.25 & TH1_Score1 <  0 ~ "Q3 (TH17-TH1-)",
    TH17_Score1 >= 0.25 & TH1_Score1 <  0 ~ "Q4 (TH17+TH1-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH1+)", "Q2 (TH17-TH1+)", "Q3 (TH17-TH1-)", "Q4 (TH17+TH1-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)


quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4act_modulescore_th1vsth17_withmeans.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TH17_Score1, y = TH1_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TH17, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) + 
  geom_text(
    data = mean,
    aes(x = TH17, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Th17-like module score", y = "Th1-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.3, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()



#th2 vs th17
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TH17_Score1 >= 0.25 & TH2_Score1 >= 0.25 ~ "Q1 (TH17+TH2+)",
    TH17_Score1 <  0.25 & TH2_Score1 >= 0.25 ~ "Q2 (TH17-TH2+)",
    TH17_Score1 <  0.25 & TH2_Score1 <  0.25 ~ "Q3 (TH17-TH2-)",
    TH17_Score1 >= 0.25 & TH2_Score1 <  0.25 ~ "Q4 (TH17+TH2-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH2+)", "Q2 (TH17-TH2+)", "Q3 (TH17-TH2-)", "Q4 (TH17+TH2-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)


quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4act_modulescore_th2vsth17_withmeans_rasterized.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TH17_Score1, y = TH2_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TH17, y = TH2, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) + 
  geom_text(
    data = mean,
    aes(x = TH17, y = TH2, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0.25, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Th17-like module score", y = "Th2-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.3, 1.5), ylim = c(-0.2, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()

#tfhtchron vs th1
quadrant_pct <- modulescores %>%
  mutate(quadrant = case_when(
    TFH_TCHRON_Score1 >= 0.25 & TH1_Score1 >= 0 ~ "Q1 (TFH_TCHRON+TH1+)",
    TFH_TCHRON_Score1 <  0.25 & TH1_Score1 >= 0 ~ "Q2 (TFH_TCHRON-TH1+)",
    TFH_TCHRON_Score1 <  0.25 & TH1_Score1 <  0 ~ "Q3 (TFH_TCHRON-TH1-)",
    TFH_TCHRON_Score1 >= 0.25 & TH1_Score1 <  0 ~ "Q4 (TFH_TCHRON+TH1-)"
  )) %>%
  count(quadrant) %>%
  mutate(pct = n / sum(n) * 100,
         label = sprintf("%.1f%%", pct))

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TFH_TCHRON+TH1+)", "Q2 (TFH_TCHRON-TH1+)", "Q3 (TFH_TCHRON-TH1-)", "Q4 (TFH_TCHRON+TH1-)"),
  x = c(1.2,  -0.1,  -0.1,  1.2),
  y = c(1.0,   1.3,  -0.2,  -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

pdf("052726_cd4act_modulescore_tfhtchronvsth2_withmeans.pdf", width = 8, height = 8, useDingbats = FALSE)
ggplot(modulescores, aes(x = TFH_TCHRON_Score1, y = TH1_Score1, color = annotation_level2)) +
  ggrastr::geom_point_rast(size = 0.4, alpha = 0.3, raster.dpi = 200) + 
  geom_point(
    data = mean,
    aes(x = TFH_TCHRON, y = TH1, fill = annotation_level2),
    shape = 21, color = "black", size = 4, stroke = 1
  ) + 
  geom_text(
    data = mean,
    aes(x = TFH_TCHRON, y = TH1, label = annotation_level2),
    color = "black", vjust = -1, size = 4
  ) +
  geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  geom_vline(xintercept = 0, color = "red", linetype = "dashed", linewidth = 0.4) +
  
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black", fontface = "bold", size = 4
  ) +
  theme_classic() +
  labs(x = "Tfh/Tchron-like module score", y = "Th1-like module score",
       color = "Cluster", fill = "Cluster") +
  coord_cartesian(xlim = c(-0.50, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)
dev.off()
```

```{r}
#4g - feature scatters of pd1 x cxcr5 in h and i
cd4_cite <- subset(cd4_object, subset = cite_seq == "TRUE")
cd4_cite <- NormalizeData(cd4_cite, assay = "ADT", normalization.method = "LogNormalize")

cd4_cite$h <- cd4_cite$annotation_level2 == "CD4.H"

p <- MyFeatureScatter(
  so = cd4_cite,
  group.by = "h",
  feature1 = "CXCR5",
  feature2 = "PDCD1.PD1.CD279",
  raster = TRUE
) + coord_cartesian(xlim = c(0, 5))

pdf("052726_featscatter_cd4.h_cxcr5xpd1.pdf", height = 6, width = 6, useDingbats = FALSE)
print(p)
dev.off()


cd4_cite$i <- cd4_cite$annotation_level2  == "CD4.I"

p <- MyFeatureScatter(
  so = cd4_cite,
  group.by = "i",
  feature1 = "CXCR5",
  feature2 = "PDCD1.PD1.CD279",
  raster = TRUE
) + coord_cartesian(xlim = c(0, 5))

pdf("052726_featscatter_cd4.i_cxcr5xpd1.pdf", height = 6, width = 6, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#4h - fr4 x cd73
p <- MyFeatureScatter(
  so = cd4_cite,
  group.by = "i",
  feature1 = "FR4",
  feature2 = "CD73.5NTD",
  raster = TRUE
)

pdf("052726_featscatter_cd4.i_fr4xcd73.pdf", height = 6, width = 6, useDingbats = FALSE)
print(p)
dev.off()

p <- MyFeatureScatter(
  so = cd4_cite,
  group.by = "h",
  feature1 = "FR4",
  feature2 = "CD73.5NTD",
  raster = TRUE
)

pdf("052726_featscatter_cd4.h_fr4xcd73.pdf", height = 6, width = 6, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#5a - mdes mapping time course of slo listeria Tet+ Cells
conds <- cd4_object@meta.data %>%
  filter(igt_number == "43") %>%
  pull(condition_detailed) %>%
  unique() %>%
  sort()

for (cond in conds) {
  
  message("Plotting: ", cond)
  
  cells_cond <- colnames(cd4_object)[
    cd4_object$igt_number == "43" &
    cd4_object$condition_detailed == cond
  ]
  
  plots_cond <- MyDimPlotHighlight(
    seurat_object         = cd4_object,
    umap_to_plot          = "mde_incremental",
    cells_to_highlight    = cells_cond,
    highlight_column_name = "annotation_level2",
    title                 = cond,
    labelclusters         = FALSE,
    highlight_raster      = TRUE,
    highlight_pixels      = c(1024, 1024),
    mycols                = palette_vector,
    highlight_size        = 4,
    highlight_alpha       = 1,
    background_alpha      = 1.0,
    pixels                = c(512, 512)
  )
  
  p <- plots_cond$plot1 +
    NoAxes() +
    NoLegend() +
    theme(legend.position = "none") +
    coord_cartesian(
      xlim = c(-2.5, 4),
      ylim = c(-2.5, 2.5)
    )
  
  pdf(
    paste0("052726_mde_igt43_", gsub("[ /]", "_", cond), ".pdf"),
    width = 6,
    height = 6,
    useDingbats = FALSE
  )
  
  print(p)
  
  dev.off()
}
```


```{r}
#5c/d - acute listeria module score scatter plots
listeria_object <- subset(cd4_object, subset = igt_number == "43")
listeria_ids <- listeria_ids <- colnames(listeria_object)

listeria_meta <- listeria_object@meta.data %>%
  rownames_to_column("cell")

clusters_keep <- c("CD4.Q","CD4.G","CD4.H", "CD4.I", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y")

modulescores <- FetchData(
  cd4_object,
  vars = c(
    "TH1_Score1",
    "TH2_Score1",
    "TH17_Score1",
    "TFH_TCHRON_Score1",
    "annotation_level2",
    "organ_simplified",
    "condition_detailed"
  )
) %>%
  rownames_to_column("cell") %>%
  mutate(is_listeria = cell %in% listeria_ids) %>%
  filter(annotation_level2 %in% clusters_keep)


listeria_d7_slo <- modulescores %>%
  filter(
    is_listeria,
    organ_simplified %in% c("spleen", "SLO"),
    condition_detailed %in% c("Lmonocytogenes_D6", "Lmonocytogenes_D10")
  )

quadrant_pct <- listeria_d7_slo %>%
  mutate(
    quadrant = case_when(
      TFH_TCHRON_Score1 >= 0 & TH1_Score1 >= 0 ~ "Q1 (TFH_TCHRON+TH1+)",
      TFH_TCHRON_Score1 <  0 & TH1_Score1 >= 0 ~ "Q2 (TFH_TCHRON-TH1+)",
      TFH_TCHRON_Score1 <  0 & TH1_Score1 <  0 ~ "Q3 (TFH_TCHRON-TH1-)",
      TFH_TCHRON_Score1 >= 0 & TH1_Score1 <  0 ~ "Q4 (TFH_TCHRON+TH1-)"
    )
  ) %>%
  count(quadrant) %>%
  mutate(
    pct = n / sum(n) * 100,
    label = sprintf("%.1f%%", pct)
  )

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TFH_TCHRON+TH1+)", "Q2 (TFH_TCHRON-TH1+)", "Q3 (TFH_TCHRON-TH1-)", "Q4 (TFH_TCHRON+TH1-)"),
  x = c(1.2, -0.1, -0.1, 1.2),
  y = c(1.0, 1.3, -0.2, -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

mean_listeria <- listeria_d7_slo %>%
  group_by(annotation_level2) %>%
  summarise(
    TFH_TCHRON = mean(TFH_TCHRON_Score1, na.rm = TRUE),
    TH1 = mean(TH1_Score1, na.rm = TRUE),
    .groups = "drop"
  )

pdf("052726_listeria_acute_th1vstfhtchron.pdf", width = 8, height = 8, useDingbats = FALSE)

ggplot() +
  ggrastr::geom_point_rast(
    data = modulescores,
    aes(x = TFH_TCHRON_Score1, y = TH1_Score1),
    color = "grey80",
    size = 0.35,
    alpha = 0.25,
    raster.dpi = 200
  ) +
  ggrastr::geom_point_rast(
    data = listeria_d7_slo,
    aes(x = TFH_TCHRON_Score1, y = TH1_Score1, color = annotation_level2),
    size = 3,
    alpha = 0.9,
    raster.dpi = 200
  ) +
  geom_point(
    data = mean_listeria,
    aes(x = TFH_TCHRON, y = TH1, fill = annotation_level2),
    shape = 21,
    color = "black",
    size = 4,
    stroke = 1
  ) +
  geom_text(
    data = mean_listeria,
    aes(x = TFH_TCHRON, y = TH1, label = annotation_level2),
    color = "black",
    vjust = -1,
    size = 4
  ) +
  geom_hline(
    yintercept = 0,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_vline(
    xintercept = 0,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black",
    fontface = "bold",
    size = 4
  ) +
  theme_classic() +
  labs(
    x = "Tfh_Tchron-like module score",
    y = "Th1-like module score",
    color = "Cluster",
    fill = "Cluster"
  ) +
  coord_cartesian(xlim = c(-0.4, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)

dev.off()

#th2 vs th17

quadrant_pct <- listeria_d7_slo %>%
  mutate(
    quadrant = case_when(
      TH17_Score1 >= 0.25 & TH2_Score1 >= 0.25 ~ "Q1 (TH17+TH2+)",
      TH17_Score1 <  0.25 & TH2_Score1 >= 0.25 ~ "Q2 (TH17-TH2+)",
      TH17_Score1 <  0.25 & TH2_Score1 <  0.25 ~ "Q3 (TH17-TH2-)",
      TH17_Score1 >= 0.25 & TH2_Score1 <  0.25 ~ "Q4 (TH17+TH2-)"
    )
  ) %>%
  count(quadrant) %>%
  mutate(
    pct = n / sum(n) * 100,
    label = sprintf("%.1f%%", pct)
  )

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH2+)", "Q2 (TH17-TH2+)", "Q3 (TH17-TH2-)", "Q4 (TH17+TH2-)"),
  x = c(1.2, -0.1, -0.1, 1.2),
  y = c(1.0, 1.3, -0.2, -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

mean_listeria <- listeria_d7_slo %>%
  group_by(annotation_level2) %>%
  summarise(
    TH17 = mean(TH17_Score1, na.rm = TRUE),
    TH2 = mean(TH2_Score1, na.rm = TRUE),
    .groups = "drop"
  )

pdf("052726_listeriad6_d10_th2vsth17.pdf", width = 8, height = 8, useDingbats = FALSE)

ggplot() +
  ggrastr::geom_point_rast(
    data = modulescores,
    aes(x = TH17_Score1, y = TH2_Score1),
    color = "grey80",
    size = 0.35,
    alpha = 0.25,
    raster.dpi = 200
  ) +
  ggrastr::geom_point_rast(
    data = listeria_d7_slo,
    aes(x = TH17_Score1, y = TH2_Score1, color = annotation_level2),
    size = 3,
    alpha = 0.9,
    raster.dpi = 200
  ) +
  geom_point(
    data = mean_listeria,
    aes(x = TH17, y = TH2, fill = annotation_level2),
    shape = 21,
    color = "black",
    size = 4,
    stroke = 1
  ) +
  geom_text(
    data = mean_listeria,
    aes(x = TH17, y = TH2, label = annotation_level2),
    color = "black",
    vjust = -1,
    size = 4
  ) +
  geom_hline(
    yintercept = 0.25,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_vline(
    xintercept = 0.25,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4 
  ) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black",
    fontface = "bold",
    size = 4
  ) +
  theme_classic() +
  labs(
    x = "Th17-like module score",
    y = "Th2-like module score",
    color = "Cluster",
    fill = "Cluster"
  ) +
  coord_cartesian(xlim = c(-0.4, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)

dev.off()
```

```{r}
#S4a - Ifng and Tbx21 in acute listeria
MyFeaturePlotHighlight <- function (seurat_object, feature, cells_to_highlight, umap_to_plot = "umap", 
    assay = "RNA", colors = viridis::viridis(10), title = "", 
    pixels = c(512, 512), highlight_size = 1, highlight_alpha = 1, 
    xlim = NULL, ylim = NULL, background_alpha = 0.1) 
{
    dim_data <- seurat_object[[umap_to_plot]]@cell.embeddings
    dim1 <- dim_data[, 1]
    dim2 <- dim_data[, 2]
    tmp_all <- data.frame(seurat_object@meta.data, dim1 = dim1, 
        dim2 = dim2)
    p_base <- ggplot2::ggplot(tmp_all) + scattermore::geom_scattermore(ggplot2::aes(x = dim1, 
        y = dim2), color = "grey", pointsize = 1, alpha = background_alpha, 
        pixels = pixels)
    feature_expr <- Seurat::GetAssayData(seurat_object, assay = assay, 
        layer = "data")[feature, ]
    tmp_highlight <- tmp_all[cells_to_highlight, ]
    tmp_highlight$feature_value <- feature_expr[cells_to_highlight]
    p_final <- p_base + ggplot2::geom_point(data = tmp_highlight, 
        ggplot2::aes(x = dim1, y = dim2, color = feature_value), 
        size = highlight_size, alpha = highlight_alpha) + ggplot2::scale_color_gradientn(colours = colors, 
        name = feature) + ggplot2::theme_void() + NoGrid() + 
        ggplot2::labs(title = title, x = paste0(umap_to_plot, 
            "_1"), y = paste0(umap_to_plot, "_2"))
    if (!is.null(xlim) || !is.null(ylim)) {
        p_final <- p_final + ggplot2::coord_cartesian(xlim = xlim, 
            ylim = ylim)
    }
    return(p_final)
}

feature <- "Tbx21"
listeria_d610 <- subset(listeria_object, subset = condition_detailed %in% c("Lmonocytogenes_D6", "Lmonocytogenes_D10"))
cells_to_highlight <- colnames(listeria_d610)
pdf("052826_list_d610_tbx21_myfeatureplot.pdf", width = 8, height = 8, useDingbats = F)
MyFeaturePlotHighlight(
  seurat_object      = cd4_object,
  feature            = feature,
  cells_to_highlight = cells_to_highlight,
  umap_to_plot       = "mde_incremental",
  assay              = "RNA",
  colors = c("lightgrey", "blue"),
  highlight_size = 3.0,
  background_alpha   = 0.25, 
  title = "Tbx21 in Listeria Infection d6/10"
)
dev.off()

feature <- "Ifng"
pdf("list_d610_ifng_myfeatureplot.pdf", width = 8, height = 8, useDingbats = F)
MyFeaturePlotHighlight(
  seurat_object      = cd4_object,
  feature            = feature,
  cells_to_highlight = cells_to_highlight,
  umap_to_plot       = "mde_incremental",
  assay              = "RNA",
  colors = c("lightgrey", "blue"),
  highlight_size = 3.0,
  background_alpha   = 0.25, 
  title = "Ifng in Listeria Infection d6/10"
)
dev.off()

#d253060
feature <- "Tbx21"
listeria_d253060 <- subset(listeria_object, subset = condition_detailed %in% c("Lmonocytogenes_D25", "Lmonocytogenes_D30", "Lmonocytogenes_D60"))
cells_to_highlight <- colnames(listeria_d253060)
pdf("list_d253060_tbx21_myfeatureplot.pdf", width = 8, height = 8, useDingbats = F)
MyFeaturePlotHighlight(
  seurat_object      = cd4_object,
  feature            = feature,
  cells_to_highlight = cells_to_highlight,
  umap_to_plot       = "mde_incremental",
  assay              = "RNA",
  colors = c("lightgrey", "blue"),
  highlight_size = 3.0,
  background_alpha   = 0.25, 
  title = "Tbx21 in Listeria Infection d25/30/60"
)
dev.off()

feature <- "Ifng"
pdf("052826_list_d253060_ifng_myfeatureplot.pdf", width = 8, height = 8, useDingbats = F)
MyFeaturePlotHighlight(
  seurat_object      = cd4_object,
  feature            = feature,
  cells_to_highlight = cells_to_highlight,
  umap_to_plot       = "mde_incremental",
  assay              = "RNA",
  colors = c("lightgrey", "blue"),
  highlight_size = 3.0,
  background_alpha   = 0.25, 
  title = "Ifng in Listeria Infection d25/30/60"
)
dev.off()
```

```{r}
#s4e
smarta_ids <- read.csv("smarta_citeseq_igt363840_2026.csv", header = FALSE)$V1
smarta_object <- subset(cd4_object, subset = cells %in% smarta_ids)

smata_meta <- smarta_object@meta.data %>%
  rownames_to_column("cell")


clusters_keep <- c("CD4.Q","CD4.G","CD4.H", "CD4.I", "CD4.R", "CD4.S", "CD4.T", "CD4.U", "CD4.X", "CD4.Y")

modulescores <- FetchData(
  cd4_object,
  vars = c(
    "TH1_Score1",
    "TH2_Score1",
    "TH17_Score1",
    "TFH_TCHRON_Score1",
    "annotation_level2",
    "organ_simplified",
    "condition_detailed"
  )
) %>%
  rownames_to_column("cell") %>%
  mutate(is_smarta = cell %in% smarta_ids) %>%
  filter(annotation_level2 %in% clusters_keep)


smarta_meta <- modulescores %>%
  filter(is_smarta)

smarta_d7_slo <- modulescores %>%
  filter(
    is_smarta,
    organ_simplified %in% c("spleen", "SLO"),
    condition_detailed %in% c("LCMVarm_D7")
  )

#th1 vs tfh
quadrant_pct <- smarta_d7_slo %>%
  mutate(
    quadrant = case_when(
      TFH_TCHRON_Score1 >= 0 & TH1_Score1 >= 0 ~ "Q1 (TFH_TCHRON+TH1+)",
      TFH_TCHRON_Score1 <  0 & TH1_Score1 >= 0 ~ "Q2 (TFH_TCHRON-TH1+)",
      TFH_TCHRON_Score1 <  0 & TH1_Score1 <  0 ~ "Q3 (TFH_TCHRON-TH1-)",
      TFH_TCHRON_Score1 >= 0 & TH1_Score1 <  0 ~ "Q4 (TFH_TCHRON+TH1-)"
    )
  ) %>%
  count(quadrant) %>%
  mutate(
    pct = n / sum(n) * 100,
    label = sprintf("%.1f%%", pct)
  )

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TFH_TCHRON+TH1+)", "Q2 (TFH_TCHRON-TH1+)", "Q3 (TFH_TCHRON-TH1-)", "Q4 (TFH_TCHRON+TH1-)"),
  x = c(1.2, -0.1, -0.1, 1.2),
  y = c(1.0, 1.3, -0.2, -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

mean_smarta <- smarta_d7_slo %>%
  group_by(annotation_level2) %>%
  summarise(
    TFH_TCHRON = mean(TFH_TCHRON_Score1, na.rm = TRUE),
    TH1 = mean(TH1_Score1, na.rm = TRUE),
    .groups = "drop"
  )

pdf("052826_lcmvarmd7_slo_th1vstfhtchron.pdf", width = 8, height = 8, useDingbats = FALSE)

ggplot() +
  ggrastr::geom_point_rast(
    data = modulescores,
    aes(x = TFH_TCHRON_Score1, y = TH1_Score1),
    color = "grey80",
    size = 0.35,
    alpha = 0.25,
    raster.dpi = 200
  ) +
  ggrastr::geom_point_rast(
    data = smarta_d7_slo,
    aes(x = TFH_TCHRON_Score1, y = TH1_Score1, color = annotation_level2),
    size = 3,
    alpha = 0.9,
    raster.dpi = 200
  ) +
  geom_point(
    data = mean_smarta,
    aes(x = TFH_TCHRON, y = TH1, fill = annotation_level2),
    shape = 21,
    color = "black",
    size = 4,
    stroke = 1
  ) +
  geom_text(
    data = mean_smarta,
    aes(x = TFH_TCHRON, y = TH1, label = annotation_level2),
    color = "black",
    vjust = -1,
    size = 4
  ) +
  geom_hline(
    yintercept = 0,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_vline(
    xintercept = 0,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black",
    fontface = "bold",
    size = 4
  ) +
  theme_classic() +
  labs(
    x = "Tfh_Tchron-like module score",
    y = "Th1-like module score",
    color = "Cluster",
    fill = "Cluster"
  ) +
  coord_cartesian(xlim = c(-0.4, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)

dev.off()

#th2 vs th17
quadrant_pct <- smarta_d7_slo %>%
  mutate(
    quadrant = case_when(
      TH17_Score1 >= 0.25 & TH2_Score1 >= 0.25 ~ "Q1 (TH17+TH2+)",
      TH17_Score1 <  0.25 & TH2_Score1 >= 0.25 ~ "Q2 (TH17-TH2+)",
      TH17_Score1 <  0.25 & TH2_Score1 <  0.25 ~ "Q3 (TH17-TH2-)",
      TH17_Score1 >= 0.25 & TH2_Score1 <  0.25 ~ "Q4 (TH17+TH2-)"
    )
  ) %>%
  count(quadrant) %>%
  mutate(
    pct = n / sum(n) * 100,
    label = sprintf("%.1f%%", pct)
  )

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH2+)", "Q2 (TH17-TH2+)", "Q3 (TH17-TH2-)", "Q4 (TH17+TH2-)"),
  x = c(1.2, -0.1, -0.1, 1.2),
  y = c(1.0, 1.3, -0.2, -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

mean_smarta <- smarta_d7_slo %>%
  group_by(annotation_level2) %>%
  summarise(
    TH17 = mean(TH17_Score1, na.rm = TRUE),
    TH2 = mean(TH2_Score1, na.rm = TRUE),
    .groups = "drop"
  )

pdf("052826_lcmvarmd7_slo_th2vsth17.pdf", width = 8, height = 8, useDingbats = FALSE)

ggplot() +
  ggrastr::geom_point_rast(
    data = modulescores,
    aes(x = TH17_Score1, y = TH2_Score1),
    color = "grey80",
    size = 0.35,
    alpha = 0.25,
    raster.dpi = 200
  ) +
  ggrastr::geom_point_rast(
    data = smarta_d7_slo,
    aes(x = TH17_Score1, y = TH2_Score1, color = annotation_level2),
    size = 3,
    alpha = 0.9,
    raster.dpi = 200
  ) +
  geom_point(
    data = mean_smarta,
    aes(x = TH17, y = TH2, fill = annotation_level2),
    shape = 21,
    color = "black",
    size = 4,
    stroke = 1
  ) +
  geom_text(
    data = mean_smarta,
    aes(x = TH17, y = TH2, label = annotation_level2),
    color = "black",
    vjust = -1,
    size = 4
  ) +
  geom_hline(
    yintercept = 0.25,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_vline(
    xintercept = 0.25,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black",
    fontface = "bold",
    size = 4
  ) +
  theme_classic() +
  labs(
    x = "Th17-like module score",
    y = "Th2-like module score",
    color = "Cluster",
    fill = "Cluster"
  ) +
  coord_cartesian(xlim = c(-0.4, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)

dev.off()

```

```{r}
#s4f
smarta_d3060_slo <- modulescores %>%
  filter(
    is_smarta,
    organ_simplified %in% c("spleen", "LN"),
    condition_detailed %in% c("LCMVarm_D30", "LCMVarm_D60")
  )



quadrant_pct <- smarta_d3060_slo %>%
  mutate(
    quadrant = case_when(
      TH17_Score1 >= 0.25 & TH2_Score1 >= 0.25 ~ "Q1 (TH17+TH2+)",
      TH17_Score1 <  0.25 & TH2_Score1 >= 0.25 ~ "Q2 (TH17-TH2+)",
      TH17_Score1 <  0.25 & TH2_Score1 <  0.25 ~ "Q3 (TH17-TH2-)",
      TH17_Score1 >= 0.25 & TH2_Score1 <  0.25 ~ "Q4 (TH17+TH2-)"
    )
  ) %>%
  count(quadrant) %>%
  mutate(
    pct = n / sum(n) * 100,
    label = sprintf("%.1f%%", pct)
  )

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TH17+TH2+)", "Q2 (TH17-TH2+)", "Q3 (TH17-TH2-)", "Q4 (TH17+TH2-)"),
  x = c(1.2, -0.1, -0.1, 1.2),
  y = c(1.0, 1.3, -0.2, -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

mean_smarta <- smarta_d3060_slo %>%
  group_by(annotation_level2) %>%
  summarise(
    TH17 = mean(TH17_Score1, na.rm = TRUE),
    TH2 = mean(TH2_Score1, na.rm = TRUE),
    .groups = "drop"
  )

pdf("052826_lcmvarmd3060_slo_th2vsth17.pdf", width = 8, height = 8, useDingbats = FALSE)

ggplot() +
  ggrastr::geom_point_rast(
    data = modulescores,
    aes(x = TH17_Score1, y = TH2_Score1),
    color = "grey80",
    size = 0.35,
    alpha = 0.25,
    raster.dpi = 200
  ) +
  ggrastr::geom_point_rast(
    data = smarta_d3060_slo,
    aes(x = TH17_Score1, y = TH2_Score1, color = annotation_level2),
    size = 3,
    alpha = 0.9,
    raster.dpi = 200
  ) +
  geom_point(
    data = mean_smarta,
    aes(x = TH17, y = TH2, fill = annotation_level2),
    shape = 21,
    color = "black",
    size = 4,
    stroke = 1
  ) +
  geom_text(
    data = mean_smarta,
    aes(x = TH17, y = TH2, label = annotation_level2),
    color = "black",
    vjust = -1,
    size = 4
  ) +
  geom_hline(
    yintercept = 0.25,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_vline(
    xintercept = 0.25,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black",
    fontface = "bold",
    size = 4
  ) +
  theme_classic() +
  labs(
    x = "Th17-like module score",
    y = "Th2-like module score",
    color = "Cluster",
    fill = "Cluster"
  ) +
  coord_cartesian(xlim = c(-0.4, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)

dev.off()

#th1 vs tfhtchron
quadrant_pct <- smarta_d3060_slo %>%
  mutate(
    quadrant = case_when(
      TFH_TCHRON_Score1 >= 0 & TH1_Score1 >= 0 ~ "Q1 (TFH_TCHRON+TH1+)",
      TFH_TCHRON_Score1 <  0 & TH1_Score1 >= 0 ~ "Q2 (TFH_TCHRON-TH1+)",
      TFH_TCHRON_Score1 <  0 & TH1_Score1 <  0 ~ "Q3 (TFH_TCHRON-TH1-)",
      TFH_TCHRON_Score1 >= 0 & TH1_Score1 <  0 ~ "Q4 (TFH_TCHRON+TH1-)"
    )
  ) %>%
  count(quadrant) %>%
  mutate(
    pct = n / sum(n) * 100,
    label = sprintf("%.1f%%", pct)
  )

quadrant_coords <- data.frame(
  quadrant = c("Q1 (TFH_TCHRON+TH1+)", "Q2 (TFH_TCHRON-TH1+)", "Q3 (TFH_TCHRON-TH1-)", "Q4 (TFH_TCHRON+TH1-)"),
  x = c(1.2, -0.1, -0.1, 1.2),
  y = c(1.0, 1.3, -0.2, -0.2)
)

quadrant_pct <- left_join(quadrant_pct, quadrant_coords, by = "quadrant")

mean_smarta <- smarta_d3060_slo %>%
  group_by(annotation_level2) %>%
  summarise(
    TFH_TCHRON = mean(TFH_TCHRON_Score1, na.rm = TRUE),
    TH1 = mean(TH1_Score1, na.rm = TRUE),
    .groups = "drop"
  )

pdf("05826_lcmvarmd3060_slo_th1vstfhtchron.pdf", width = 8, height = 8, useDingbats = FALSE)

ggplot() +
  ggrastr::geom_point_rast(
    data = modulescores,
    aes(x = TFH_TCHRON_Score1, y = TH1_Score1),
    color = "grey80",
    size = 0.35,
    alpha = 0.25,
    raster.dpi = 200
  ) +
  ggrastr::geom_point_rast(
    data = smarta_d3060_slo,
    aes(x = TFH_TCHRON_Score1, y = TH1_Score1, color = annotation_level2),
    size = 3,
    alpha = 0.9,
    raster.dpi = 200
  ) +
  geom_point(
    data = mean_smarta,
    aes(x = TFH_TCHRON, y = TH1, fill = annotation_level2),
    shape = 21,
    color = "black",
    size = 4,
    stroke = 1
  ) +
  geom_text(
    data = mean_smarta,
    aes(x = TFH_TCHRON, y = TH1, label = annotation_level2),
    color = "black",
    vjust = -1,
    size = 4
  ) +
  geom_hline(
    yintercept = 0,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_vline(
    xintercept = 0,
    color = "red",
    linetype = "dashed",
    linewidth = 0.4
  ) +
  geom_text(
    data = quadrant_pct,
    aes(x = x, y = y, label = label),
    inherit.aes = FALSE,
    color = "black",
    fontface = "bold",
    size = 4
  ) +
  theme_classic() +
  labs(
    x = "Tfh_Tchron-like module score",
    y = "Th1-like module score",
    color = "Cluster",
    fill = "Cluster"
  ) +
  coord_cartesian(xlim = c(-0.4, 1.5), ylim = c(-0.5, 1.5)) +
  scale_color_manual(values = palette_vector) +
  scale_fill_manual(values = palette_vector)

dev.off()
```


```{r}
#6a - resting cd4 citeseq heatmap
cd4_cite <- subset(cd4_object, subset = cite_seq == "TRUE")
cd4_cite <- subset(
  cd4_cite,
  subset = !annotation_level2 %in% c("CD4.wN", "CD4.wZ", "CD4.P", "CD4.wM")
)

DefaultAssay(cd4_cite) <- "ADT"

citeseq_markers <- c(
  "CD62L","CD44","FR4","CD55.DAF",
  "LY6C1-LY6C2","CD45RB","CD5","CD69"
)

cluster_order <- levels(factor(cd4_cite$annotation_level2))
cd4_cite$annotation_level2 <- factor(cd4_cite$annotation_level2, levels = cluster_order)
Idents(cd4_cite) <- cd4_cite$annotation_level2

adt_counts <- GetAssayData(cd4_cite, assay = "ADT", layer = "counts")

present_adt <- intersect(citeseq_markers, rownames(adt_counts))
adt_counts <- adt_counts[present_adt, , drop = FALSE]

cell_totals <- Matrix::colSums(GetAssayData(cd4_cite, assay = "ADT", layer = "counts"))
cell_totals[cell_totals == 0] <- NA

adt_cp10k <- sweep(adt_counts, 2, cell_totals, "/") * 10000

avg_cp10k <- sapply(cluster_order, function(clust) {
  cells_use <- WhichCells(cd4_cite, idents = clust)
  if (length(cells_use) == 1) {
    as.numeric(adt_cp10k[, cells_use])
  } else {
    Matrix::rowMeans(adt_cp10k[, cells_use, drop = FALSE], na.rm = TRUE)
  }
})

avg_cp10k <- as.matrix(avg_cp10k)
rownames(avg_cp10k) <- present_adt
colnames(avg_cp10k) <- cluster_order

marker_order <- c(
  "CD62L","CD44","FR4","CD55.DAF",
  "LY6C1-LY6C2","CD45RB","CD5","CD69"
)
marker_order <- marker_order[marker_order %in% rownames(avg_cp10k)]
avg_cp10k <- avg_cp10k[marker_order, , drop = FALSE]
avg_cp10k_log1p <- log1p(avg_cp10k)

blue_white_red <- colorRampPalette(c("blue", "white", "red"))(100)

pdf("052826_adt_cp10k_lpg10_heatmap.pdf", width = 10, height = 5, useDingbats = FALSE)
pheatmap(
  avg_cp10k_log1p,
  color = blue_white_red,
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  fontsize_row = 10,
  fontsize_col = 8,
  angle_col = 45,
  border_color = "darkgray",
  cellwidth = 12,
  cellheight = 12,
  main = "Mean ADT expression (log1p(CP10K))"
)
dev.off()
```

```{r}
#6c - iv- clusters in nlts
cd4_object$is_resting_ivneg <- cd4_object$annotation_level2 %in% c("CD4.A", "CD4.B", "CD4.C", "CD4.D", "CD4.E", "CD4.F") & cd4_object$gating_strategy %in% c(" IV- CD3+", "IV- CD45.2+ CD3e+", "IV- CD45+ CD3+ CD44+", "IV- CD45+ CD3e+", " IV- CD45+ CD3e+ CD44+ Derp1 Tet +/+", " IV- CD45+ CD3e+ CD44+ Thy1.1- and Thy1.1+ (OT1)", " IV- CD45+ CD3e+ Derp1 tet- and IV- CD45+ CD3e+ Derp1 tet+", "IV- CD45+ CD3e+ Thy1.1- and Thy1.1+ (OT1)")
cells_ivneg <- colnames(cd4_object)[cd4_object$is_resting_ivneg]
plots_ivneg <- MyDimPlotHighlight(
  seurat_object         = cd4_object,
  umap_to_plot          = "mde_incremental",
  cells_to_highlight    = cells_ivneg,
  highlight_column_name = "annotation_level2",
  title                 = "Resting IV- Cells highlighted",
  labelclusters = FALSE,
  highlight_raster = T,
  highlight_pixels =  c(1024, 1024),
  mycols = palette_vector,
  highlight_size = 4,
  highlight_alpha = 1,
  background_alpha = 1.0,
  pixels = c(512,512)
)

p <- print(plots_ivneg$plot1 + NoAxes() + NoGrid()) + NoLegend() + theme(legend.position = "none") + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5))

pdf("052826_ivneg_resting_highlighted.pdf", width = 8, height =8, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#6d - top dge between resting clusters
resting_analysis <- readRDS("ttlist_in_Resting.Rds")
cluster_order <- c("CD4.A","CD4.B","CD4.C","CD4.D","CD4.E","CD4.F")
markers_long <- imap_dfr(resting_analysis, function(df, nm) {
  df %>%
    as.data.frame() %>%
    mutate(
      cluster = str_remove(nm, "_vs_AllResting$"),
      gene = SYMBOL
    ) %>%
    select(gene, cluster, logFC, AveExpr, P.Value, adj.P.Val, t, B)
}) %>%
  filter(cluster %in% cluster_order)

top10 <- markers_long %>%
  filter(logFC > 0, adj.P.Val < 1e-20) %>%
  group_by(cluster) %>%
  slice_max(order_by = logFC, n = 10, with_ties = FALSE) %>%
  ungroup()

gene_order <- top10 %>%
  mutate(cluster = factor(cluster, levels = cluster_order)) %>%
  arrange(cluster, desc(logFC)) %>%
  distinct(gene, .keep_all = TRUE) %>%
  pull(gene)

lfc_mat_df <- markers_long %>%
  filter(gene %in% gene_order) %>%
  select(gene, cluster, logFC) %>%
  distinct()

lfc_mat <- lfc_mat_df %>%
  pivot_wider(
    names_from = cluster,
    values_from = logFC,
    values_fill = 0
  ) %>%
  as.data.frame()

rownames(lfc_mat) <- lfc_mat$gene
lfc_mat$gene <- NULL

missing_cols <- setdiff(cluster_order, colnames(lfc_mat))
for (cl in missing_cols) {
  lfc_mat[[cl]] <- 0
}

lfc_mat <- lfc_mat[, cluster_order, drop = FALSE]
lfc_mat <- lfc_mat[gene_order, , drop = FALSE]
lfc_mat <- as.matrix(lfc_mat)

lfc_mat[lfc_mat > 2] <- 2
lfc_mat[lfc_mat < -2] <- -2

blue_white_red <- colorRampPalette(c("blue", "white", "red"))(100)

p <- pheatmap(
  lfc_mat,
  color = blue_white_red,
  breaks = seq(-2, 2, length.out = 101),
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  cellwidth = 12,
  cellheight = 12,
  fontsize_row = 6,
  main = "Resting CD4 DE genes (top10 genes, all cluster logFC)"
)

pdf("052826_resting_cd4_logFC_heatmap.pdf", width = 12, height = 40, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#6e - highlighting cd62l+cd69+
cd4_cite <- NormalizeData(cd4_cite, assay = "ADT", normalization.method = "LogNormalize")
adt <- GetAssayData(cd4_cite, assay = "ADT", layer = "data")

cd62l_feat <- "CD62L"
cd69_feat <- "CD69"

cd62l_thresh <- 5
cd69_thresh <- 5


cd4_cite$is_cd62l_cd69 <-
  (adt[cd62l_feat, ]  > cd62l_thresh) &
  (adt[cd69_feat, ] > cd69_thresh)

p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_cd62l_cd69",
  split.by = NULL,
  raster = FALSE,
  highlight_size = 0.25,
  highlight_alpha = 1.0,
  cols = magma(100)
)
pdf("052826_cd69_cd62l_dimplot.pdf", width = 8, height = 8, useDingbats = FALSE)
print(p)
dev.off()
```

```{r}
#s5c - #taking sajani et al., making my own umap from their data
obj <- readRDS("b6spleenb6ln.Rds")
obj <- NormalizeData(obj)
obj <- FindVariableFeatures(obj)
obj <- ScaleData(obj)
obj <- RunPCA(obj)

obj$immgen_clusters <- obj$level2_final

obj <- FindNeighbors(obj, dims = 1:30)
obj <- RunUMAP(obj, dims = 1:30)

#just to find which resolution gives me 5 clusters
for (res in c(0.2, 0.3, 0.4, 0.5, 0.6)) {
  obj <- FindClusters(obj, resolution = res)
  cat("\nresolution =", res, "\n")
  print(table(Idents(obj)))
} #0.2 gave me 5 clusters

obj <- FindClusters(obj, resolution = 0.2)
obj$clusters_0.2 <- Idents(obj)

DimPlot(obj, group.by = "clusters_0.2", label = TRUE)

#trying to overlay?
ref_embedding <- as.data.frame(Embeddings(cd4_object, reduction = "mde_incremental"))
colnames(ref_embedding) <- c("UMAP_1", "UMAP_2")

query_embedding <- as.data.frame(Embeddings(obj, reduction = "mde_incremental_level2"))
colnames(query_embedding) <- c("UMAP_1", "UMAP_2")
query_embedding$cluster_named <- as.character(obj$cluster_named)


cluster_colors <- c(
  "TUND"  = "#E69F00",
  "TIFN"  = "#56B4E9",  
  "TQ"    = "#009E73",
  "TMEM"  = "#CC79A7", 
  "TTCR"  = "#0072B2"
)
p <- ggplot() +
  geom_point(
    data = ref_embedding,
    aes(x = UMAP_1, y = UMAP_2),
    color = "lightgray",
    size = 0.3,
    alpha = 0.5
  ) +
  geom_point(
    data = query_embedding,
    aes(x = UMAP_1, y = UMAP_2, color = cluster_named),
    size = 0.3,
    alpha = 0.8
  ) +
  theme_classic() +
  labs(
    title = "Query Clusters on Reference Embedding",
    color = "Cluster"
  ) +
  guides(color = guide_legend(override.aes = list(size = 3)))

print(p)
p + scale_color_manual(values = cluster_colors)

```

```{r}
#s5c - heatmap comparing igt resting cd4 clusters to sajani et al clusters
#heatmap to see each of the 5 clusters
Idents(obj) <- obj$clusters_0.2

markers <- FindAllMarkers(
  obj,
  only.pos = TRUE,
  min.pct = 0.25,
  logfc.threshold = 0.25
)

top10 <- markers %>%
  group_by(cluster) %>%
  slice_max(order_by = avg_log2FC, n = 10) %>%
  arrange(cluster, desc(avg_log2FC))

ordered_genes <- top10$gene

avg_exp <- AverageExpression(
  obj,
  features = ordered_genes,
  group.by = "clusters_0.2",
  assays = "RNA"
)$RNA

heat_mat <- t(scale(t(avg_exp)))

heat_mat_ordered <- heat_mat[ordered_genes, ]

annotation_row <- data.frame(
  cluster = top10$cluster
)
rownames(annotation_row) <- ordered_genes

cluster_sizes <- table(top10$cluster)
gaps_row <- cumsum(cluster_sizes)

pheatmap(
  heat_mat_ordered,
  color = colorRampPalette(c("darkblue", "white", "red"))(100),
  cluster_rows = FALSE,
  cluster_cols = FALSE,
  annotation_row = annotation_row,
  fontsize_col = 10,
  cellwidth = 12,
  cellheight = 12,
  border_color = "lightgray"
)

Idents(obj) <- obj$clusters_0.2

obj <- RenameIdents(
  obj,
  "0" = "TUND",
  "1" = "TIFN",
  "2" = "TQ",
  "3" = "TMEM",
  "4" = "TTCR"
)


obj$cluster_named <- Idents(obj)


DimPlot(
  obj,
  reduction = "mde_incremental_level2",
  group.by = "cluster_named",
  label = TRUE
)


df_out <- data.frame(
  Cell_ID = colnames(obj),
  batch = "b6spleenb6ln",
  new_annotation = obj$cluster_named
)

write.csv(df_out, "cell_annotations.csv", row.names = FALSE)
```

```{r}
#7a - rna dotplot of markers for flow
gene_markers <- c(
  "Sell", "Cd44", "Cd69" ,"Cxcr5", "Cxcr6", "Izumo1r",
  "Nt5e", "Pdcd1", "Klrg1", "Ly6c1", "Ly6c2", "Il1rl1", "Il23r")

DefaultAssay(cd4_object) <- "RNA"

genes_use <- intersect(gene_markers, rownames(cd4_object[["RNA"]]))
stopifnot(length(genes_use) > 0)

clusters_drop <- c("CD4.wN", "CD4.wZ", "CD4.P", "CD4.wM")

cd4_rna <- subset(
  cd4_object,
  subset = !(annotation_level2 %in% clusters_drop)
)
DefaultAssay(cd4_rna) <- "RNA"

genes_use <- intersect(gene_markers, rownames(cd4_rna[["RNA"]]))
stopifnot(length(genes_use) > 0)

cd4_rna <- NormalizeData(cd4_rna, assay = "RNA", normalization.method = "LogNormalize")
dp <- DotPlot(
  cd4_rna,
  features = genes_use,
  group.by = "annotation_level2",
  assay = "RNA"
)

dp_df <- dp$data
dp_df$features.plot <- factor(dp_df$features.plot, levels = rev(genes_use))

base_size <- 10
axis_size <- 9

p_rna <- ggplot(dp_df, aes(x = id, y = features.plot)) +
  geom_point(
    aes(size = pct.exp, fill = avg.exp.scaled),
    shape = 21,
    color = "black",
    stroke = 0.12
  ) +
  scale_fill_gradient2(
    low = "darkblue",
    mid = "white",
    high = "red",
    midpoint = 0,
    oob = squish,
    name = "Avg expr (scaled)"
  ) +
  scale_size_continuous(
    name = "% expressing",
    range = c(0.5, 4),
    breaks = c(0, 25, 50, 75, 100),
    limits = c(0, 100)
  ) +
  scale_y_discrete(expand = expansion(mult = c(0.04, 0.04))) +
  scale_x_discrete(expand = expansion(mult = c(0.04, 0.04))) +
  theme_bw(base_size = base_size) +
  theme(
    axis.title = element_blank(),
    axis.text.x = element_text(
      size = axis_size,
      angle = 90,
      vjust = 0.5,
      hjust = 1,
      margin = margin(t = 1)
    ),
    axis.text.y = element_text(
      size = axis_size,
      lineheight = 0.85,
      margin = margin(r = 1)
    ),
    panel.grid = element_blank(),
    panel.border = element_rect(linewidth = 0.3),
    plot.margin = margin(2, 2, 2, 2),
    legend.title = element_text(size = base_size),
    legend.text  = element_text(size = base_size - 1)
  ) +
  guides(
    size = guide_legend(title = "% expressing"),
    fill = guide_colorbar(title = "Avg expr (scaled)")
  )
pdf("052826_RNA_dotplot_updated.pdf", width = 4.375, height = 2.5, useDingbats = FALSE)
print(p_rna)
dev.off()
```

```{r}
#7b - citeseq dotplot
cd4_cite <- subset(cd4_object, subset = cite_seq == "TRUE") |>
  subset(subset = !annotation_level2 %in% c("CD4.wN", "CD4.wZ", "CD4.P", "CD4.wM")) |>
  NormalizeData(assay = "ADT", normalization.method = "LogNormalize")

marker_order <- c(
  "CD62L", "CD44", "CD69" ,"CXCR5", "CXCR6.CD186", "FR4", "CD73.5NTD",
  "PDCD1.PD1.CD279", "KLRG1", "LY6C1-LY6C2"
)
grp <- factor(cd4_cite$annotation_level2)

adt_data <- GetAssayData(cd4_cite, assay = "ADT", layer = "data")
present_markers <- intersect(marker_order, rownames(adt_data))

adt_avg <- sapply(levels(grp), function(g) {
  cells <- which(grp == g)
  rowMeans(adt_data[present_markers, cells, drop = FALSE])
}) |> as.matrix()

df_plot <- as.data.frame(adt_avg) |>
  rownames_to_column("Marker") |>
  pivot_longer(-Marker, names_to = "Cluster", values_to = "expr") |>
  mutate(across(c(Marker, Cluster), trimws),
         expr = as.numeric(expr)) |>
  group_by(Marker) |>
  mutate(expr_scaled = pmax(pmin(as.numeric(scale(expr)), 2), -2)) |>
  ungroup() |>
  mutate(
    expr_size = pmax(pmin(expr, quantile(expr, 0.99, na.rm = TRUE)) * (1 + expr_scaled / 2), 0.01),
    Marker    = factor(Marker,  levels = rev(present_markers)),
    Cluster   = factor(Cluster, levels = levels(grp))
  )

p_dot <- ggplot(df_plot, aes(x = Cluster, y = Marker)) +
  geom_point(aes(size = expr_size, fill = expr_scaled),
             shape = 21, color = "black", stroke = 0.25) +
  scale_size_continuous(range = c(0.3, 4.5), name = "Expression (raw ADT, z-weighted)") +
  scale_fill_gradient2(low = "darkblue", mid = "white", high = "red",
                       midpoint = 0, limits = c(-2, 2), name = "Expression (z-score; capped)") +
  scale_x_discrete(expand = expansion(mult = c(0.02, 0.02))) +
  theme_classic(base_size = 11) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  labs(title = "ADT markers (scaled color + raw expression size)", x = NULL, y = NULL)

pdf("052826_adt_expression_dotplot_scaled.pdf", width = 7.6, height = 4, useDingbats = FALSE)
print(p_dot)
dev.off()
```

```{r}
#7d - citeseq gating
cd4_cite <- subset(cd4_object, subset = cite_seq == "TRUE")
cd4_cite <- NormalizeData(cd4_cite, assay = "ADT", normalization.method = "LogNormalize")
adt <- GetAssayData(cd4_cite, assay = "ADT", layer = "data")

#genes_use <- c( "Cxcr5","Sell","Cd44","Cxcr6","Izumo1r","Nt5e","Il1rl1","Pdcd1","Il23r","Ly6c1","Ly6c2","Klrg1")
cd4_cite <- NormalizeData(cd4_cite, assay = "RNA", normalization.method = "LogNormalize")
rna <- GetAssayData(cd4_cite, assay = "RNA", layer = "data")
#cd4_object = NULL
top10 <- function(x) unname(quantile(x, 0.90, na.rm = TRUE))
top5 <- function(x) unname(quantile(x, 0.95, na.rm = TRUE))
top1 <- function(x) unname(quantile(x, 0.99, na.rm = TRUE))
top2 <- function(x) unname(quantile(x, 0.98, na.rm = TRUE))
top20 <- function(x) unname(quantile(x, 0.80, na.rm = TRUE))
top30 <- function(x) unname(quantile(x, 0.70, na.rm = TRUE))
top50 <- function(x) unname(quantile(x, 0.50, na.rm = TRUE))

cd44_cut  <- top10(adt["CD44", ])
cd44_thresh <- 5
cd62l_cut <- top10(adt["CD62L", ])
cd62l_thresh <- 5
cxcr6_cut <- top1(adt["CXCR6.CD186", ])
cxcr5_cut <- top10(adt["CXCR5", ])
pd1_cut   <- top10(adt["PDCD1.PD1.CD279", ])
ly6c_cut <- top5(adt["LY6C1-LY6C2", ])
st2_cut <- top30(adt["IL1RL1.ST2", ])
klrg1_cut <- top10(adt["KLRG1", ])
klrg1_thresh <- 5
ly6c_thresh <- 4

il23r_vals <- rna["Il23r", , drop = TRUE]
il23r_cut <- top10(il23r_vals)

cxcr6_vals <- rna["Cxcr6", , drop = TRUE]
cxcr5_vals <- rna["Cxcr5", , drop = TRUE]
il1rl1_vals <- rna["Il1rl1", drop = TRUE]


cd4_cite$is_g <-
  (adt["CD44", ]            > cd44_thresh)  &
  (adt["CD62L", ] < cd62l_thresh) &
  (adt["FR4", ] > 4) &
  (adt["CD73.5NTD", ] > 5) &
  (rna["Cxcr6", ]     == 0) &
  (adt["CXCR5", ]           < cxcr5_cut) & #less than top50
  (adt["PDCD1.PD1.CD279", ] < pd1_cut) #less than top50


p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_g",
  split.by = NULL,
 #highlight_pixels = c(512, 512),
 raster = F,
  highlight_size = 0.5,
  highlight_alpha = 1.0 ,
  cols = magma(100)
) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void()+ NoGrid() + NoLegend()
p 
pdf(
  file = "G_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()



cd4_cite$is_I <-
  (adt["CD44", ]            > cd44_thresh)  &
  (adt["CD62L", ] < cd62l_thresh) &
  (rna["Cxcr6", ]     == 0) &
  (adt["CXCR5", ]         < cxcr5_cut) & #used top1
  (adt["PDCD1.PD1.CD279", ] > pd1_cut) #used top1


p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_I",
  split.by = NULL,
 # highlight_pixels = c(512, 512),
  highlight_size = 0.5,
 raster = F,
  highlight_alpha = 1.0,
  cols = magma(100)) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void() + NoGrid() + NoLegend()

pdf(
  file = "I_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()


cd4_cite$is_H <-
  (adt["CD44", ]            > cd44_thresh)  &
  (adt["CXCR5", ]         > cxcr5_cut) & #top10
  (adt["PDCD1.PD1.CD279", ] > pd1_cut) #top10


p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_H",
  split.by = NULL,
  #highlight_pixels = c(512, 512),
  raster = F,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  cols = magma(100)
) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void() +  NoGrid() + NoLegend()


pdf(
  file = "H_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()


 cd4_cite$is_TU <-
  (adt["CD44", ]  > cd44_thresh) &
  (adt["CD62L", ] < cd62l_thresh) &
  (rna["Cxcr6", ] > 0) &
 # (adt["LY6C1-LY6C2", ] <= ly6c_thresh) &
 (adt["KLRG1", ] > klrg1_thresh) &
  (rna["Il1rl1", ] > 0)


p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_TU",
  split.by = NULL,
 # highlight_pixels = c(512, 512),
 raster = F,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  cols = magma(100)
) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void()+ NoGrid() + NoLegend()

pdf(
  file = "TU_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()

cd4_cite$is_XY <-
  (adt["CD44", ]  > cd44_thresh) &
  (adt["CD62L", ] < cd62l_thresh) &
  (rna["Cxcr6", ] > 0) &
 (adt["IL1RL1.ST2", ] < st2_cut) &
  (adt["LY6C1-LY6C2", ] < ly6c_thresh) &
 #  (adt["KLRG1", ] < klrg1_thresh) &
  (rna["Il23r", ] > 1)

 p<- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_XY",
  split.by = NULL,
 # highlight_pixels = c(512, 512),
 raster = F,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  cols = magma(100)
)  + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void() + NoGrid() + NoLegend()


pdf(
  file = "clXY_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()


cd4_cite$is_Q <-
  (adt["CD44", ]  > cd44_thresh) &
  (rna["Cxcr6", ] > 0) &
  (adt["CD62L", ] < cd62l_thresh) &
  (rna["Il1rl1", ] == 0) &
  (adt["KLRG1", ] < klrg1_thresh) &
  (adt["LY6C1-LY6C2", ] < ly6c_thresh) &
  (rna["Il23r", ] == 0)

p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_Q",
  split.by = NULL,
  #highlight_pixels = c(512, 512),
  raster = F,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  cols = magma(100)
) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void() + NoGrid() + NoLegend()

pdf(
  file = "Q_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()

cd4_cite$is_RS <-
  (adt["CD44", ]  > cd44_thresh) &
  (adt["CD62L", ] < cd62l_thresh) &
  (rna["Cxcr6", ] > 0) &
  (rna["Il1rl1", ] == 0) &
   (adt["KLRG1", ] > klrg1_thresh) &
  (adt["LY6C1-LY6C2", ] > ly6c_thresh)

 p <- MyDimPlotHighlightDensity(
  seurat_object = cd4_cite,
  umap_to_plot = "mde_incremental",
  group.by = "is_RS",
  split.by = NULL,
  #highlight_pixels = c(512, 512),
  raster = F,
  highlight_size = 0.5,
  highlight_alpha = 1.0,
  cols = magma(100)
) + coord_cartesian(xlim = c(-2.5, 4), ylim = c(-2.5, 2.5)) + theme_void() + NoGrid() + NoLegend()

pdf(
  file = "RS_dimplotdensity.pdf",
  width = 5,
  height = 5,
  useDingbats = FALSE
)
print(p)
dev.off()
```

